graph TD
    user-service-->|"HTTP Verb: GET<br/>Arguments: [@PathVariable('id') Long departmentId]<br/>Return: com.dailycodebuffer.department.entity.Department<br/>Endpoint function: com.dailycodebuffer.department.controller.DepartmentController.findDepartmentById"|department-service
