graph TD
    ts-inside-payment-service-->|"HTTP Verb: POST<br/>Arguments: [@RequestBody DrawBackInfo info, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: inside_payment.controller.InsidePaymentController.drawBack"|ts-inside-payment-service
    ts-food-service-->|"HTTP Verb: GET<br/>Arguments: [@PathVariable String tripId, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: travel.controller.TravelController.getRouteByTripId"|ts-travel-service
    ts-rebook-service-->|"HTTP Verb: GET<br/>Arguments: [@PathVariable String name, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: train.controller.TrainController.retrieveByName"|ts-train-service
    ts-route-plan-service-->|"HTTP Verb: GET<br/>Arguments: [@PathVariable String routeId, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: route.controller.RouteController.queryById"|ts-route-service
    ts-cancel-service-->|"HTTP Verb: PUT<br/>Arguments: [@RequestBody Order orderInfo, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: other.controller.OrderOtherController.saveOrderInfo"|ts-order-other-service
    ts-admin-travel-service-->|"HTTP Verb: GET<br/>Arguments: [@RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: travel2.controller.Travel2Controller.adminQueryAll"|ts-travel2-service
    ts-preserve-other-service-->|"HTTP Verb: GET<br/>Arguments: [@PathVariable String accountId, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: security.controller.SecurityController.check"|ts-security-service
    ts-travel-plan-service-->|"HTTP Verb: POST<br/>Arguments: [@RequestBody RoutePlanInfo info, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: plan.controller.RoutePlanController.getCheapestRoutes"|ts-route-plan-service
    ts-admin-order-service-->|"HTTP Verb: POST<br/>Arguments: [@RequestBody Order order, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: other.controller.OrderOtherController.addcreateNewOrder"|ts-order-other-service
    ts-admin-route-service-->|"HTTP Verb: GET<br/>Arguments: [@RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: route.controller.RouteController.queryAll"|ts-route-service
    ts-admin-basic-info-service-->|"HTTP Verb: DELETE<br/>Arguments: [@PathVariable String configName, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: config.controller.ConfigController.deleteConfig"|ts-config-service
    ts-cancel-service-->|"HTTP Verb: GET<br/>Arguments: [@PathVariable String orderId, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: order.controller.OrderController.getOrderById"|ts-order-service
    ts-travel-service-->|"HTTP Verb: GET<br/>Arguments: [@PathVariable String name, @RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: train.controller.TrainController.retrieveByName"|ts-train-service
    ts-admin-travel-service-->|"HTTP Verb: GET<br/>Arguments: [@RequestHeader HttpHeaders headers]<br/>Return: org.springframework.http.HttpEntity<br/>Endpoint function: travel.controller.TravelController.adminQueryAll"|ts-travel-service
